# general settings for image SR training
name: train_CATANet_x4_finetune
model_type: CATANetModel
scale: 4
num_gpu: auto
manual_seed: 3407
# dataset and data loader settings
datasets:
  train:
    task: SR
    name: DIV2K
    type: PairedImageDataset
    dataroot_gt: datasets/DIV2K/DIV2K_HR
    dataroot_lq: datasets/DIV2K/DIV2K_LR_bicubic/x4
    filename_tmpl: '{}x4'
    io_backend:
      type: disk

    gt_size: 256
    use_hflip: true
    use_rot: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 8
    batch_size_per_gpu: 16
    dataset_enlarge_ratio: 100
    prefetch_mode: 'cuda'
    pin_memory: true

  val_0:
    name: Set5
    type: PairedImageDataset
    dataroot_gt: datasets/Set5/HR
    dataroot_lq: datasets/Set5/LR_bicubic/X4
    filename_tmpl: '{}x4'
    io_backend:
      type: disk
  val_1:
    name: Set14
    type: PairedImageDataset
    dataroot_gt: datasets/Set14/HR
    dataroot_lq: datasets/Set14/LR_bicubic/X4
    filename_tmpl: '{}x4'
    io_backend:
      type: disk

# network structures
network_g:
  type: CATANet
  upscale: 4

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  optim_g:
    type: Adam
    lr: !!float 2e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [125000, 200000, 225000, 237500]
    gamma: 0.5

  total_iter: 250000


  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean
# validation settings
val:
  val_freq: !!float 2500
  save_img: false

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr_pt
      crop_border: 4
      test_y_channel: true

    ssim:
      type: calculate_ssim_pt
      crop_border: 4
      test_y_channel: true



# logging settings
logger:
  print_freq: 200
  save_checkpoint_freq: !!float 2500
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500