_BASE_: "../COCO-Detection/faster_rcnn_R_50_FPN_3x.yaml"

DATASETS:
  TRAIN: ("human_parts_val",)
  TEST: ("human_parts_val",)

DATALOADER:
  NUM_WORKERS: 2

SOLVER:
  IMS_PER_BATCH: 2
  BASE_LR: 0.0005
  MAX_ITER: 18000
  STEPS: (12000, 15000)
  CHECKPOINT_PERIOD: 1000

MODEL:
  WEIGHTS: "C:/models/detectron2-main/model_final_280758.pkl"
  ROI_HEADS:
    NUM_CLASSES: 7

OUTPUT_DIR: "./output/human_parts_val_only"
TEST:
  EVAL_PERIOD: 2000


